### ISSUE TITLE
Classification issue for Fuzzing Symbolic Expressions (ICSE 2021)

### ISSUE THREAD

**Issue by rainoftime** [wcventure/FuzzingPaper#19]
Hi,

I noticed that the paper _Fuzzing Symbolic Expressions_ (ICSE 2021) is classified as "SMT Fuzzing".
However, according to its abstract and preprint (https://arxiv.org/pdf/2102.06580), it is more about constraint solving, similar to the one _Just Fuzz It: Solving Floating-Point Constraints Using Coverage-guided Fuzzing_ (FSE 2019)

**Comment by wcventure** [comment]
Thank you for informing us
