### ISSUE TITLE
missing links

### ISSUE THREAD

**Issue by vanhauser-thc** [wcventure/FuzzingPaper#39]
why hunting for interesting new papers I found two links that point to nowhere:

same-coverage-less-bloat-accelerating-binary-only-fuzzing-with-coverage-preserving-coverage-guided-tracing-ccs-2021 =
https://people.cs.vt.edu/snagy2/papers/21CCS.pdf

spotfuzzer-static-instrument-and-fuzzing-windows-cots-2022 = https://arxiv.org/abs/2201.07938

there might be more. would have done a PR but no time, sorry!

**Comment by wcventure** [comment]
Hi, 

The link is right.
I think you should use the web page link [wcventure.github.io/fuzzingpaper](https://wcventure.github.io/FuzzingPaper), instead of README.md on Github.
If you have any questions, please let me know.

Thank you.
Cheng
