### ISSUE TITLE
Categorization, Paper and Code for FreeFuzz

### ISSUE THREAD

**Issue by Anjiang-Wei** [wcventure/FuzzingPaper#44]
First of all, I greatly appreciate your efforts on setting up this website collecting so many interesting fuzzing papers for researchers around the world! Below is a small issue that I noticed:
`Free Lunch for Testing: Fuzzing Deep-Learning Libraries from Open Source` (ICSE'22) may be better to be categorized as [API Testing/Fuzzing](https://github.com/wcventure/FuzzingPaper#api-testingfuzzing) because this paper targets fuzzing Deep Learning libraries (i.e., Python APIs) instead of DL models. So it would be great if the paper could also be put under `API Testing/Fuzzing`.

The link for `Free Lunch for Testing: Fuzzing Deep-Learning Libraries from Open Source` is https://cs.stanford.edu/~anjiang/papers/WeiETAL22FreeFuzz.pdf

Also, the code is open source https://github.com/ise-uiuc/FreeFuzz

Please let me know if there is anything unclear. Thanks!

**Comment by wcventure** [comment]
Thanks, I agree with you.
