### ISSUE TITLE
Hi, do you think the category "Fuzzing Machine Learning Model" is too broad and misleading?

### ISSUE THREAD

**Issue by haoyang9804** [wcventure/FuzzingPaper#61]
I think we can remain the following papers in this category

+ MDPFuzz: Testing Models Solving Markov Decision Processes
+ RapidFuzz: Accelerating fuzzing via Generative Adversarial Networks
+ CoCoFuzzing: Testing Neural Code Models with Coverage-Guided
+ Fuzz Testing based Data Augmentation to Improve Robustness of Deep Neural Networks
+ Coverage Guided Differential Adversarial Testing of Deep Learning Systems
+ CAGFuzz: Coverage-Guided Adversarial Generative Fuzzing Testing of Deep Learning Systems
+ DeepHunter: A Coverage-Guided Fuzz Testing Framework for Deep Neural Networks
+ TensorFuzz: Debugging Neural Networks with Coverage-Guided Fuzzing
+ DLFuzz: Differential Fuzzing Testing of Deep Learning Systems

As for others, except for Graph-based Fuzz Testing for Deep Learning Inference Engines, they belong to another category possibly titled "Fuzzing Deep Learning Libraries".

As for Graph-based Fuzz Testing for Deep Learning Inference Engines, a deep learning inference engine is a compiler-like tool (not a compiler but contains compilation). I'd like to categorize it into another new category, "Fuzzing Deep Learning Compilers". In this category, there are also several other works, such as:

+ Fuzzing Deep Learning Compilers with HirGen [ISSTA '23]
+ NNSmith: Generating Diverse and Valid Test Cases for Deep Learning Compilers [ASPLOS '23]

Do you think it's a good idea to re-organize these papers? After the reorganization, I'd like to add some papers belonging to "Fuzzing Deep Learning Compilers" category.

**Comment by wcventure** [comment]
Yes, I quite agree with you about that.  I think the category "Fuzzing Machine Learning Model" is too broad. 
Can you create a pull request according to your idea?

**Comment by haoyang9804** [comment]
> Yes, I quite agree with you about that. I think the category "Fuzzing Machine Learning Model" is too broad. Can you create a pull request according to your idea?

Hi, I have create a [pull request](https://github.com/wcventure/FuzzingPaper/pull/64). Please take a look.
To be honest, I'm not an expert in fuzzing deep learning libraries so the paper listed may not be complete.
I think we can also create a new subsection titled compiler fuzzing. But since I have created one [here](https://haoyang9804.github.io/CompilerCorrectness/), I think you can put this link about maintaining compiler correctness (including compiler fuzzing) in the README if you like.

**Comment by wcventure** [comment]
```https://haoyang9804.github.io/CompilerCorrectness/```
Great!
